jwt:
  secret: t4kGirScDnr4wpeJBudhyPDvbIVb/b7dnEFpDAd0vuhEXV0tNfoc/ZL6fvF5p3C1rY306OgtV/DmTnNwmYd4Yg==
  expiration: 1800000
  refresh-expiration: 604800000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/newbit
    username: swcamp
    password: swcamp
  jpa:
    hibernate:
      ddl-auto: none  # 기존 테이블 건드리지 않도록
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # 콘솔에 SQL 보기
